services:
  - type: web
    name: travel-bharat
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 8080
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
